
networks:
  reefer-sense-network: 
    driver: bridge

services:

  iot-data-processor:
    container_name: "iot-data-processor"
    image: ${DOCKER_REGISTRY-}iotdataprocessor
    build:
      context: .
      dockerfile: iot-data-processor/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__ServiceBus__ConnectionString=Endpoint=sb://sb-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - AppSettings__ServiceBus__QueueName=iot-gateway-queue
    networks:
      - reefer-sense-network 

  iot-gateway:
    container_name: "iot-gateway"
    image: ${DOCKER_REGISTRY-}iotgateway
    build:
      context: .
      dockerfile: iot-gateway/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__ServiceBus__ConnectionString=Endpoint=sb://sb-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - AppSettings__ServiceBus__QueueName=iot-gateway-queue
    networks:
      - reefer-sense-network 

  iot-telegram-simulator:
    container_name: "iot-telegram-simulator"
    image: ${DOCKER_REGISTRY-}iottelegramsimulator
    build:
      context: .
      dockerfile: iot-telegram-simulator/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__IotGatewayServer=iot-gateway
      - AppSettings__Port=9000
    volumes:
      - ./iot-telegram-simulator/data:/app/data
    networks:
      - reefer-sense-network 

  sb-emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge  
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - sqledge
    networks:
      - reefer-sense-network

  sqledge:
    container_name: "sqledge"
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    networks:
      - reefer-sense-network

  sqlserver:
    container_name: reefer-sense-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1450:1433"
    environment:
      MSSQL_SA_PASSWORD: "ReeferSense@2025"
      ACCEPT_EULA: ${ACCEPT_EULA}
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    networks:
      - reefer-sense-network 

volumes:
  sqlserver_data:
