# /pipelines/templates/docker-buildpush.yml
parameters:
  containerRegistryServiceConnection: ''                 # e.g., 'acr-dev'
  repository: ''                                         # e.g., 'iot-gateway'
  dockerfilePath: ''                                     # e.g., 'Dockerfile.iogw'
  buildContext: '$(Pipeline.Workspace)/publish/app'      # default context from publish
  tags: |
    $(Build.SourceBranchName)-$(Build.BuildId)
    $(Build.SourceBranchName)-latest

jobs:
- job: docker_build_push
  displayName: Docker Build & Push
  steps:
  - download: current
    artifact: publish

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: ${{ parameters.containerRegistryServiceConnection }}

  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate (Azure Artifacts)'
    inputs:
      nuGetServiceConnections: 'ReeferSense-Artifacts-Connection' 
      nuGetConfigPath: '$(Build.SourcesDirectory)/NuGet.config'

  - bash: |
        if [ -n "$VSS_NUGET_EXTERNAL_FEED_ENDPOINTS" ]; then
            echo "${VSS_NUGET_EXTERNAL_FEED_ENDPOINTS}"
            # Write to a file (no output to logs)
            printf %s "$VSS_NUGET_EXTERNAL_FEED_ENDPOINTS" > "$(Pipeline.Workspace)/nuget_auth.json"
            # Basic sanity: print byte length only (safe)
            echo "nuget_auth.json bytes: $(wc -c < "$(Pipeline.Workspace)/nuget_auth.json")"
        else
            echo "$VSS_NUGET_EXTERNAL_FEED_ENDPOINTS is EMPTY at agent scope"
            exit 1         
        fi
    displayName: "NuGet auth JSON to file"


  - task: Docker@2
    displayName: Build & Push
    env:
     DOCKER_BUILDKIT: '1'
    inputs:
      command: buildAndPush
      repository: ${{ parameters.repository }}
      containerRegistry: ${{ parameters.containerRegistryServiceConnection }}
      Dockerfile: ${{ parameters.dockerfilePath }}
      buildContext: '$(Build.SourcesDirectory)'
      arguments: >
        --secret id=nuget_auth,src=$(Pipeline.Workspace)/nuget_auth.json
      tags: ${{ parameters.tags }}
