# /pipelines/templates/docker-buildpush.yml
parameters:
  containerRegistryServiceConnection: ''   # e.g., 'acr-dev'
  repository: ''                           # e.g., 'iot-gateway'
  dockerfilePath: ''                       # e.g., 'Dockerfile.iogw'
  buildContext: '$(Pipeline.Workspace)/publish/app'   # default context from publish
  tags: |
    $(Build.SourceBranchName)-$(Build.BuildId)
    $(Build.SourceBranchName)-latest

jobs:
- job: docker_build_push
  displayName: Docker Build & Push
  steps:
  - download: current
    artifact: publish

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: ${{ parameters.containerRegistryServiceConnection }}

  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate (Azure Artifacts)'

  - task: Docker@2
    displayName: Build & Push
    inputs:
      command: buildAndPush
      repository: ${{ parameters.repository }}
      containerRegistry: ${{ parameters.containerRegistryServiceConnection }}
      Dockerfile: ${{ parameters.dockerfilePath }}
      buildContext: '$(Build.SourcesDirectory)'
      arguments: >
        --build-arg VSS_NUGET_EXTERNAL_FEED_ENDPOINTS="$(VSS_NUGET_EXTERNAL_FEED_ENDPOINTS)"
      tags: ${{ parameters.tags }}
